name: Build and Deploy

on:
  push:
    branches:
      - main  # Remplacez "main" par le nom de votre branche principale

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install  # Si vous utilisez npm pour gérer vos dépendances

    - name: Build
      run: npm run build  # Remplacez cette commande par la commande de construction de votre projet

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.2.0
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages  # Remplacez "gh-pages" par la branche que vous utilisez pour GitHub Pages
        FOLDER: build  # Remplacez "build" par le dossier de construction de votre projet